services:
  - type: web
    name: skin-size
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
